-- Smoltbot Traces Table
-- Stores all tool invocation traces from monitored agents

CREATE TABLE traces (
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  tool_name TEXT NOT NULL,
  action_type TEXT NOT NULL,  -- 'allow', 'deny' (Phase 2), 'error'
  params JSONB,               -- Tool parameters
  result JSONB,               -- Tool result
  duration_ms INTEGER,
  trace_json JSONB NOT NULL,  -- Full AAP trace for extensibility
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common query patterns

-- Primary query pattern: get traces for an agent, most recent first
CREATE INDEX idx_traces_agent_timestamp ON traces(agent_id, timestamp DESC);

-- Filter by tool name (e.g., show all file writes)
CREATE INDEX idx_traces_tool_name ON traces(tool_name);

-- Filter by action type (e.g., show all denials)
CREATE INDEX idx_traces_action_type ON traces(action_type);

-- Time-based queries (e.g., traces in last hour)
CREATE INDEX idx_traces_timestamp ON traces(timestamp DESC);

-- Compound index for filtering by agent and tool
CREATE INDEX idx_traces_agent_tool ON traces(agent_id, tool_name);

-- GIN index for JSONB queries on params (e.g., find traces by file path)
CREATE INDEX idx_traces_params_gin ON traces USING GIN (params jsonb_path_ops);

-- Constraints

-- Ensure action_type is one of the valid values
ALTER TABLE traces ADD CONSTRAINT chk_action_type
  CHECK (action_type IN ('allow', 'deny', 'error'));

-- Ensure timestamp is positive (Unix epoch milliseconds)
ALTER TABLE traces ADD CONSTRAINT chk_timestamp_positive
  CHECK (timestamp > 0);

-- Ensure duration is non-negative when present
ALTER TABLE traces ADD CONSTRAINT chk_duration_non_negative
  CHECK (duration_ms IS NULL OR duration_ms >= 0);

-- Comments for documentation
COMMENT ON TABLE traces IS 'Stores all tool invocation traces from Smoltbot-monitored agents';
COMMENT ON COLUMN traces.id IS 'Unique trace ID (UUID generated by agent)';
COMMENT ON COLUMN traces.agent_id IS 'Identifier for the agent instance';
COMMENT ON COLUMN traces.timestamp IS 'Unix timestamp in milliseconds when tool was invoked';
COMMENT ON COLUMN traces.tool_name IS 'Name of the tool that was called';
COMMENT ON COLUMN traces.action_type IS 'Whether the tool call was allowed, denied, or errored';
COMMENT ON COLUMN traces.params IS 'Parameters passed to the tool';
COMMENT ON COLUMN traces.result IS 'Result returned by the tool (may be truncated)';
COMMENT ON COLUMN traces.duration_ms IS 'How long the tool execution took in milliseconds';
COMMENT ON COLUMN traces.trace_json IS 'Full AAP trace object for extensibility';
COMMENT ON COLUMN traces.created_at IS 'When the trace was inserted into the database';
