import { readFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

/**
 * Plugin configuration interface
 *
 * Zero-config by design:
 * - agentId: Generated by `smoltbot init`, stored locally
 * - batchSize/timeout: Optional tuning, sensible defaults
 *
 * No credentials needed - the API endpoint is embedded in the plugin.
 */
export interface SmoltbotConfig {
  agentId: string;
  enabled: boolean;
  batchSize: number;
  timeout: number;
}

/**
 * Configuration stored in ~/.smoltbot/config.json
 */
export interface StoredConfig {
  agentId: string;
  createdAt: string;
  version: string;
}

/**
 * Path to the smoltbot configuration directory
 */
export const CONFIG_DIR = join(homedir(), '.smoltbot');

/**
 * Path to the configuration file
 */
export const CONFIG_FILE = join(CONFIG_DIR, 'config.json');

/**
 * Load stored configuration from disk
 */
export function loadStoredConfig(): StoredConfig | null {
  if (!existsSync(CONFIG_FILE)) {
    return null;
  }

  try {
    const content = readFileSync(CONFIG_FILE, 'utf-8');
    return JSON.parse(content) as StoredConfig;
  } catch {
    return null;
  }
}

/**
 * Get the full plugin configuration
 *
 * Reads agent ID from ~/.smoltbot/config.json (created by `smoltbot init`).
 * No credentials needed - traces go to our API automatically.
 */
export function getConfig(): SmoltbotConfig | null {
  const storedConfig = loadStoredConfig();

  if (!storedConfig) {
    return null;
  }

  // Optional overrides via environment (for power users/testing)
  const enabled = process.env.SMOLTBOT_ENABLED !== 'false';
  const batchSize = parseInt(process.env.SMOLTBOT_BATCH_SIZE || '1', 10);
  const timeout = parseInt(process.env.SMOLTBOT_TIMEOUT || '5000', 10);

  return {
    agentId: storedConfig.agentId,
    enabled,
    batchSize,
    timeout,
  };
}

/**
 * Get the agent dashboard URL
 */
export function getAgentUrl(agentId: string): string {
  return `https://mnemom.ai/agent/${agentId}`;
}
